/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.DialogWait;
import BLL.HoTro;
import DAO.daoNhapHang;
import DTO.dtoPhieuNhap;
import java.awt.Color;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingWorker;

/**
 *
 * @author bumte
 */
public class FormMain extends javax.swing.JFrame {

    public static boolean login = false;
    public static List<dtoPhieuNhap> listPhieuNhap = daoNhapHang.GetListPhieuNhap(2);
    public static Locale quocTich = new Locale("Vietnamese", "vi");

    public static NhapHangForm2 formNhapHang2 = new NhapHangForm2();
    public static SanPhamForm formSanPham = new SanPhamForm();
    public static FormBlank blank = new FormBlank();
    public static Color Selected = new Color(204, 204, 204);
    public static Color White = new Color(255, 255, 255);

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        LoadForm(formSanPham, "Sản phẩm");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        nuoc = new com.toedter.components.JLocaleChooser();
        jPanel1 = new javax.swing.JPanel();
        btnQLSanPham = new javax.swing.JToggleButton();
        btnQLPhieuNhap = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        db = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblGio = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("QL Sản phẩm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Nhập hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("QL Sản phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nuoc.setSelectedIndex(11);
        nuoc.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÝ BÁN HÀNG THANH HIỀN");
        setMinimumSize(new java.awt.Dimension(1421, 853));
        setPreferredSize(new java.awt.Dimension(1200, 853));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1498, 50));

        btnQLSanPham.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnQLSanPham);
        btnQLSanPham.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLSanPham.setSelected(true);
        btnQLSanPham.setText("QUẢN LÝ SẢN PHẨM");
        btnQLSanPham.setBorder(null);
        btnQLSanPham.setBorderPainted(false);
        btnQLSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLSanPham.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checkmark_30px.png"))); // NOI18N
        btnQLSanPham.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checkmark_30px.png"))); // NOI18N
        btnQLSanPham.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnQLSanPhamStateChanged(evt);
            }
        });
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });

        btnQLPhieuNhap.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnQLPhieuNhap);
        btnQLPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQLPhieuNhap.setText("QUẢN LÝ NHẬP HÀNG");
        btnQLPhieuNhap.setBorder(null);
        btnQLPhieuNhap.setBorderPainted(false);
        btnQLPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLPhieuNhap.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checkmark_30px.png"))); // NOI18N
        btnQLPhieuNhap.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checkmark_30px.png"))); // NOI18N
        btnQLPhieuNhap.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnQLPhieuNhapStateChanged(evt);
            }
        });
        btnQLPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPhieuNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnQLPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1200, 700));

        db.setBackground(new java.awt.Color(51, 51, 51));
        db.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        db.setOpaque(true);
        db.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dbStateChanged(evt);
            }
        });
        jScrollPane1.setViewportView(db);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1498, 20));

        lblGio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGio.setForeground(new java.awt.Color(255, 255, 255));
        lblGio.setText("12:02:20");

        lblNgay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(255, 255, 255));
        lblNgay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgay.setText("Thứ 5 ngày 12 tháng 12 năm 2020");

        lblVersion.setForeground(new java.awt.Color(255, 255, 204));
        lblVersion.setText("Version V1.1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 717, Short.MAX_VALUE)
                .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblGio)
                .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblVersion))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
////---------------------This action ------------------------------------------------------------
//

                HoTro.ClockExample(lblGio, lblNgay);
                lblVersion.setText("Version: V" + FormLoading.thisVersion);
//
//// -----------------------------------------------------------------------

                return null;
            }
        };
        mySwingWorker.execute();


    }//GEN-LAST:event_formWindowActivated

    private void btnQLSanPhamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnQLSanPhamStateChanged
        if (btnQLSanPham.isSelected()) {
            btnQLSanPham.setBackground(Selected);
        } else {
            btnQLSanPham.setBackground(White);
        }
    }//GEN-LAST:event_btnQLSanPhamStateChanged

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed

        LoadForm(formSanPham, "SẢN PHẨM");

    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void dbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dbStateChanged

    }//GEN-LAST:event_dbStateChanged

    private void btnQLPhieuNhapStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnQLPhieuNhapStateChanged
        if (btnQLPhieuNhap.isSelected()) {
            btnQLPhieuNhap.setBackground(Selected);
        } else {
            btnQLPhieuNhap.setBackground(White);
        }
    }//GEN-LAST:event_btnQLPhieuNhapStateChanged

    private void btnQLPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPhieuNhapActionPerformed
//        DialogWait wait = new DialogWait();
//        SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
//            @Override
//            protected Void doInBackground() throws Exception {
//---------------------This action ------------------------------------------------------------

        LoadForm(formNhapHang2, "NHẬP HÀNG");

//// -----------------------------------------------------------------------
//                wait.close();
//                return null;
//            }
//        };
//
//        mySwingWorker.execute();
//        if (!formNhapHang.isDisplayable()) {
//            wait.makeWait("Đang tải phiếu nhập...");
//        }

    }//GEN-LAST:event_btnQLPhieuNhapActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormLoading.frm.dispose();
        FormLoading form = new FormLoading();
        form.setVisible(true);
        System.exit(1);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void LoadForm(JInternalFrame form, String name) {
        if (form == null) {
            form = blank;
        }
        if (!form.isDisplayable()) {

            db.add(form, name, db.getTabCount());

        }
        db.repaint();
        db.revalidate();
        db.setSelectedComponent(form);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnQLPhieuNhap;
    private javax.swing.JToggleButton btnQLSanPham;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane db;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblVersion;
    public static com.toedter.components.JLocaleChooser nuoc;
    // End of variables declaration//GEN-END:variables
}
