/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.HoTro;
import BLL.phieuNhapCtrl;
import java.awt.Font;
import java.util.Date;
import BLL.phieuNhapCtrl;
import static BLL.phieuNhapCtrl.*;
import static BLL.phieuNhapCtrl.ListPhieuNhap;
import static BLL.phieuNhapCtrl.XoaCTPhieuNhap;
import static BLL.phieuNhapCtrl.fillGioHang;
import static BLL.phieuNhapCtrl.phieuNhapDangChon;
import BLL.sanPhamCtrl;
import DTO.dtoCTPhieuNhap;
import DTO.dtoPhieuNhap;
import DTO.dtoSanPham;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author bumte
 */
public class NhapHangForm2 extends javax.swing.JInternalFrame {

    private static int colPhieuNhapBangPhieuNhap = 4;
    private static int colNhaCungCapPhieuNhap = 5;
    private static int colChiTietPhieuNhap = 3;
    private static dtoSanPham sanPhamChon = null;
    public static CardLayout cl;
    public static CardLayout clNutbam;

    /**
     * Creates new form NhapHangForm2
     */
    public NhapHangForm2() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        cl = (CardLayout) clNhapHang.getLayout();
        clNutbam = (CardLayout) clNutThaoTac.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        cbbChucNang = new javax.swing.JComboBox();
        tabPhieuNhap = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnlThongTinNhaCungCapVaPhieuNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenPhieuNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtThongTinNCC = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDaThanhToan = new javax.swing.JFormattedTextField();
        txtConLai = new javax.swing.JFormattedTextField();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        clNutThaoTac = new javax.swing.JPanel();
        btnTaoMoi = new javax.swing.JButton();
        clNutThaoTac2 = new javax.swing.JPanel();
        btnNhapPhieuNhap = new javax.swing.JButton();
        btnTaoPhieuNhapMoi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        clNhapHang = new javax.swing.JPanel();
        clNhaphangCard1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        clNhapHangCard2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        lblTongTien = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        pnlChonSP = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        clpBangSP1 = new javax.swing.JScrollPane();
        tblChonSanPham = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        cbbTrangThaiPhieuNhap = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        lblTenBang = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();

        jScrollPane3.setMinimumSize(new java.awt.Dimension(1200, 700));

        jPanel10.setPreferredSize(new java.awt.Dimension(1200, 583));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setMinimumSize(new java.awt.Dimension(100, 700));

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField2");

        jTextField4.setText("jTextField2");

        jTextField5.setText("jTextField2");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel10);

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setPreferredSize(new java.awt.Dimension(600, 583));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel12);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel9);

        cbbChucNang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XÓA", "SỬA" }));

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tabPhieuNhap.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabPhieuNhap.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnlThongTinNhaCungCapVaPhieuNhap.setBackground(new java.awt.Color(204, 204, 204));
        pnlThongTinNhaCungCapVaPhieuNhap.setMaximumSize(new java.awt.Dimension(500, 32767));
        pnlThongTinNhaCungCapVaPhieuNhap.setPreferredSize(new java.awt.Dimension(500, 408));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN PHIẾU NHẬP");

        txtTenPhieuNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenPhieuNhap.setDisabledTextColor(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tên phiếu nhập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bên bán");

        txtThongTinNCC.setColumns(20);
        txtThongTinNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtThongTinNCC.setRows(2);
        txtThongTinNCC.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        jScrollPane2.setViewportView(txtThongTinNCC);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Đã thanh toán");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Còn lại");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ngày nhập");

        txtDaThanhToan.setForeground(new java.awt.Color(0, 0, 102));
        txtDaThanhToan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtDaThanhToan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDaThanhToan.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        txtDaThanhToan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDaThanhToan.setSelectionEnd(txtDaThanhToan.getText().length()-1);
        txtDaThanhToan.setValue(0);
        txtDaThanhToan.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDaThanhToanCaretUpdate(evt);
            }
        });
        txtDaThanhToan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDaThanhToanFocusGained(evt);
            }
        });

        txtConLai.setForeground(new java.awt.Color(0, 0, 102));
        txtConLai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtConLai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConLai.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        txtConLai.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtConLai.setSelectionEnd(txtConLai.getText().length()-1);
        txtConLai.setValue(0);
        txtConLai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConLaiFocusGained(evt);
            }
        });

        txtNgayNhap.setForeground(new java.awt.Color(0, 0, 153));
        txtNgayNhap.setDate(new Date());
        txtNgayNhap.setDateFormatString("dd / MM / yyyy hh:mm:ss");
        txtNgayNhap.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txtNgayNhap.setDoubleBuffered(false);
        txtNgayNhap.setFont(txtNgayNhap.getFont().deriveFont(txtNgayNhap.getFont().getStyle() | java.awt.Font.BOLD, txtNgayNhap.getFont().getSize()+2));
        txtNgayNhap.getSpinner().setFont(new Font("Some-Font-Name", Font.ITALIC, 15));
        txtNgayNhap.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNgayNhapAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        clNutThaoTac.setBackground(new java.awt.Color(204, 204, 204));
        clNutThaoTac.setLayout(new java.awt.CardLayout());

        btnTaoMoi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });
        clNutThaoTac.add(btnTaoMoi, "cl1");

        btnNhapPhieuNhap.setBackground(new java.awt.Color(0, 102, 204));
        btnNhapPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNhapPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapPhieuNhap.setText("NHẬP");
        btnNhapPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapPhieuNhapActionPerformed(evt);
            }
        });

        btnTaoPhieuNhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_30px_1.png"))); // NOI18N
        btnTaoPhieuNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuNhapMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clNutThaoTac2Layout = new javax.swing.GroupLayout(clNutThaoTac2);
        clNutThaoTac2.setLayout(clNutThaoTac2Layout);
        clNutThaoTac2Layout.setHorizontalGroup(
            clNutThaoTac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clNutThaoTac2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnNhapPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(121, 121, 121))
            .addComponent(btnTaoPhieuNhapMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clNutThaoTac2Layout.setVerticalGroup(
            clNutThaoTac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clNutThaoTac2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNhapPhieuNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoPhieuNhapMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        clNutThaoTac.add(clNutThaoTac2, "cl2");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_menu_vertical_20px.png"))); // NOI18N
        jButton5.setText("<html><a href='#'>CHỌN</a><html>");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinNhaCungCapVaPhieuNhapLayout = new javax.swing.GroupLayout(pnlThongTinNhaCungCapVaPhieuNhap);
        pnlThongTinNhaCungCapVaPhieuNhap.setLayout(pnlThongTinNhaCungCapVaPhieuNhapLayout);
        pnlThongTinNhaCungCapVaPhieuNhapLayout.setHorizontalGroup(
            pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clNutThaoTac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConLai))
                    .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDaThanhToan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenPhieuNhap))
                    .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                        .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlThongTinNhaCungCapVaPhieuNhapLayout.setVerticalGroup(
            pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDaThanhToan)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinNhaCungCapVaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConLai)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(clNutThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clNhapHang.setLayout(new java.awt.CardLayout());

        clNhaphangCard1.setName("ChuaTaoPhieuNhap"); // NOI18N
        clNhaphangCard1.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel10.setText("Cần nhập đầy đủ thông tin phiếu nhập và nhà cung cấp để chọn sản phẩm nhập");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_jog_reverse_100px.png"))); // NOI18N

        javax.swing.GroupLayout clNhaphangCard1Layout = new javax.swing.GroupLayout(clNhaphangCard1);
        clNhaphangCard1.setLayout(clNhaphangCard1Layout);
        clNhaphangCard1Layout.setHorizontalGroup(
            clNhaphangCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clNhaphangCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        clNhaphangCard1Layout.setVerticalGroup(
            clNhaphangCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clNhaphangCard1Layout.createSequentialGroup()
                .addGroup(clNhaphangCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clNhaphangCard1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel11))
                    .addGroup(clNhaphangCard1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel10)))
                .addContainerGap(605, Short.MAX_VALUE))
        );

        clNhapHang.add(clNhaphangCard1, "cl1");

        clNhapHangCard2.setName("pnl1"); // NOI18N

        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 661));

        jPanel5.setPreferredSize(new java.awt.Dimension(500, 797));

        tblGioHang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CTPN", "STT", "THÔNG TIN SẢN PHẨM", "XÓA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblGioHang.setRowHeight(100);
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioHang);
        if (tblGioHang.getColumnModel().getColumnCount() > 0) {
            tblGioHang.getColumnModel().getColumn(0).setMinWidth(0);
            tblGioHang.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblGioHang.getColumnModel().getColumn(0).setMaxWidth(0);
            tblGioHang.getColumnModel().getColumn(1).setMinWidth(20);
            tblGioHang.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblGioHang.getColumnModel().getColumn(1).setMaxWidth(70);
            tblGioHang.getColumnModel().getColumn(3).setMinWidth(50);
            tblGioHang.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblGioHang.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        lblTongTien.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(153, 0, 51));
        lblTongTien.setText("TỔNG TIỀN:");

        txtTongTien.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(153, 0, 51));
        txtTongTien.setText("12000000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTongTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        clNhapHangCard2.setLeftComponent(jPanel3);

        pnlChonSP.setPreferredSize(new java.awt.Dimension(600, 811));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("jLabel4");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("jLabel4");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblChonSanPham.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblChonSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123213213", null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Quy cách", "ĐVT", "Tỉ trọng", "<html><p style='text-align: center'>Tổng<br>khối lượng<p><html>", "<html><p style='text-align:center'>Tổng <br> độ dài</p><html>", "Số lượng", "<html><p style='text-align: center'>Đơn giá<br>lẽ<p><html>", "<html><p style='text-align: center'>Đơn giá<br>sỉ<p><html>", "sp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChonSanPham.setFillsViewportHeight(true);
        tblChonSanPham.setGridColor(new java.awt.Color(0, 0, 0));
        tblChonSanPham.setRowHeight(80);
        tblChonSanPham.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblChonSanPhamAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblChonSanPham.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblChonSanPhamFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblChonSanPhamFocusLost(evt);
            }
        });
        tblChonSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChonSanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblChonSanPhamMousePressed(evt);
            }
        });
        clpBangSP1.setViewportView(tblChonSanPham);
        if (tblChonSanPham.getColumnModel().getColumnCount() > 0) {
            tblChonSanPham.getColumnModel().getColumn(0).setMinWidth(50);
            tblChonSanPham.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblChonSanPham.getColumnModel().getColumn(0).setMaxWidth(50);
            tblChonSanPham.getColumnModel().getColumn(4).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(4).setMaxWidth(0);
            tblChonSanPham.getColumnModel().getColumn(5).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(5).setMaxWidth(0);
            tblChonSanPham.getColumnModel().getColumn(6).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(6).setMaxWidth(0);
            tblChonSanPham.getColumnModel().getColumn(7).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(7).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(7).setMaxWidth(0);
            tblChonSanPham.getColumnModel().getColumn(8).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(8).setMaxWidth(0);
            tblChonSanPham.getColumnModel().getColumn(9).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(9).setMaxWidth(0);
            tblChonSanPham.getColumnModel().getColumn(10).setMinWidth(0);
            tblChonSanPham.getColumnModel().getColumn(10).setPreferredWidth(0);
            tblChonSanPham.getColumnModel().getColumn(10).setMaxWidth(0);
        }

        txtTimKiem.setText("jTextField1");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jButton3)
                .addGap(230, 230, 230))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clpBangSP1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(clpBangSP1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlChonSPLayout = new javax.swing.GroupLayout(pnlChonSP);
        pnlChonSP.setLayout(pnlChonSPLayout);
        pnlChonSPLayout.setHorizontalGroup(
            pnlChonSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChonSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChonSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChonSPLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlChonSPLayout.setVerticalGroup(
            pnlChonSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonSPLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clNhapHangCard2.setRightComponent(pnlChonSP);

        clNhapHang.add(clNhapHangCard2, "cl2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlThongTinNhaCungCapVaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
            .addComponent(pnlThongTinNhaCungCapVaPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );

        tabPhieuNhap.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/Capture.JPG")), jPanel1); // NOI18N

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel11.setMinimumSize(new java.awt.Dimension(300, 100));

        tblPhieuNhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Thông tin phiếu nhập", "Ngày nhập", "id", "Chi tiết phiếu nhập", "pn", "ncc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhap.setRowHeight(70);
        tblPhieuNhap.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tblPhieuNhap.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblPhieuNhap.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblPhieuNhapAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblPhieuNhap);
        if (tblPhieuNhap.getColumnModel().getColumnCount() > 0) {
            tblPhieuNhap.getColumnModel().getColumn(1).setMinWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(1).setMaxWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(2).setMinWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(2).setMaxWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(3).setMinWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(3).setMaxWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(4).setMinWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(4).setMaxWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(5).setMinWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblPhieuNhap.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_sync_30px.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cbbTrangThaiPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbbTrangThaiPhieuNhap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbTrangThaiPhieuNhap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTrangThaiPhieuNhapItemStateChanged(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_30px_6.png"))); // NOI18N
        jButton2.setText("Mới");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbTrangThaiPhieuNhap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbTrangThaiPhieuNhap)
                .addContainerGap())
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane5.setViewportView(txtLog);

        lblTenBang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenBang.setText("Danh sách phiếu nhập");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_30px.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblText.setText("jLabel17");
        lblText.setToolTipText("");
        lblText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblText.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblText.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTextAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lblText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lblTenBang, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenBang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1307, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(252, 252, 252))
        );

        tabPhieuNhap.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/Capture1.JPG")), jPanel2); // NOI18N

        getContentPane().add(tabPhieuNhap);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDaThanhToanCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDaThanhToanCaretUpdate

    }//GEN-LAST:event_txtDaThanhToanCaretUpdate

    private void txtDaThanhToanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaThanhToanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaThanhToanFocusGained

    private void txtConLaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConLaiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConLaiFocusGained

    private void btnNhapPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapPhieuNhapActionPerformed
        if (NhapHang()) {
            ThongBao.ThongBao("Đã nhập hàng thành công", "Thông báo");
        }
        ;
    }//GEN-LAST:event_btnNhapPhieuNhapActionPerformed

    private void txtNgayNhapAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgayNhapAncestorAdded
        txtNgayNhap.setLocale(FormMain.nuoc.getLocale());
    }//GEN-LAST:event_txtNgayNhapAncestorAdded

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        System.out.println("Đã mở");
        phieuNhapCtrl.fillGioHang(tblGioHang, ListPhieuNhap.get(2).getCtPhieuNhap());
        phieuNhapCtrl.fillPhieuNhap(tblPhieuNhap, ListPhieuNhap);
        sanPhamCtrl.LoadBangSanPham(tblChonSanPham, "");
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblChonSanPhamAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblChonSanPhamAncestorAdded

    }//GEN-LAST:event_tblChonSanPhamAncestorAdded

    private void tblChonSanPhamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblChonSanPhamFocusGained
//        tblChonSanPham.setRowSelectionAllowed(true);
//        tblGioHang.setRowSelectionAllowed(false);
//        if (tblChonSanPham.getSelectedRowCount() > 0) {
//            BTNCTPhieuNhapStatus(false);
//
//        } else {
//            BTNCTPhieuNhapStatus(false);
//        }
    }//GEN-LAST:event_tblChonSanPhamFocusGained

    private void tblChonSanPhamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblChonSanPhamFocusLost
        //        if (tblChonSanPham.getSelectedRowCount() > 0) {
        //            BTNCTPhieuNhapStatus(false);
        //        } else {
        //            BTNCTPhieuNhapStatus(true);
        //        }
    }//GEN-LAST:event_tblChonSanPhamFocusLost

    private void tblChonSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChonSanPhamMouseClicked
        if (tblChonSanPham.getSelectedRowCount() > 0) {
            //            dtoSanPham sp = null;
            //            sp = (dtoSanPham) tblChonSanPham.getValueAt(tblChonSanPham.getSelectedRow(), 10);
            //            setThongTinSPNhap(sp);
//            OnClickTableSanPham();

        }
    }//GEN-LAST:event_tblChonSanPhamMouseClicked

    private void lblTextAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTextAncestorAdded

    }//GEN-LAST:event_lblTextAncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //        jdlChonNCC jdl = new jdlChonNCC(new JFrame(), true);
        //        jdl.setVisible(true);
        //        dtoPhieuNhap phieuNhapMoi = jdlChonNCC.phieuNhapMoi;
        //        if (phieuNhapMoi != null) {
        //            cbbTrangThaiPhieuNhap.setSelectedIndex(0);
        //
        //        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbbTrangThaiPhieuNhapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTrangThaiPhieuNhapItemStateChanged

        //        if (cbbTrangThaiPhieuNhap.getItemCount() > 2) {
        //            if (cbbTrangThaiPhieuNhap.getItemCount() > 0) {
        //                DialogWait wait = new DialogWait();
        //                SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
        //                    @Override
        //                    protected Void doInBackground() throws Exception {
        //                        //---------------------This action ------------------------------------------------------------
        //
        //                        MyComboBox mb = (MyComboBox) cbbTrangThaiPhieuNhap.getSelectedItem();
        //                        trangThaiPhieuNhap = mb.toInt();
        //                        index = 0;
        //                        ReloadData();
        //                        if (listPhieuNhap.size() <= 0) {
        //                            ThongBao.ThongBao("Không có phiếu nhập nào đã lưu!", "Thông báo");
        //                            wait.close();
        //
        //                            return null;
        //
        //                        }
        //                        loadAllTable(index);
        //                        OnChangeStatusPhieuNhap();
        //                        //// -----------------------------------------------------------------------
        //                        wait.close();
        //                        return null;
        //
        //                    }
        //                };
        //                //
        //                mySwingWorker.execute();
        //                wait.makeWait("Đang chạy...");
        //            }
        //        }
        //
    }//GEN-LAST:event_cbbTrangThaiPhieuNhapItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //        DialogWait wait = new DialogWait();
        //        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
        //
        //            @Override
        //            protected Void doInBackground() throws Exception {
        //                index = 0;
        //                ReloadData();
        //                loadAllTable(index);
        //
        //                wait.close();
        //                return null;
        //            }
        //        };
        //
        //        worker.execute();
        //        wait.makeWait("Đang làm mới dữ liệu");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tblPhieuNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMousePressed
        if (tblPhieuNhap.getSelectedRowCount() < 1) {
            return;
        }
        int rowSelect = tblPhieuNhap.getSelectedRow();
        if (evt.getClickCount() == 2) {
            dtoPhieuNhap pn = (dtoPhieuNhap) tblPhieuNhap.getValueAt(rowSelect, colPhieuNhapBangPhieuNhap);
            phieuNhapCtrl.SetPhieuNhap(pn);
            SetThongTinPhieuNhap(rowSelect);
            phieuNhapCtrl.fillGioHang(tblGioHang, phieuNhapDangChon.getCtPhieuNhap());
            double tongTien = TinhTongTien();
            txtTongTien.setText(HoTro.DoubleToString(tongTien) + "VND");
//            setThongTinNhaCungCap(false);
            TrangThaiGiaoDien(2);
        }

    }//GEN-LAST:event_tblPhieuNhapMousePressed

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked

    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void tblPhieuNhapAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblPhieuNhapAncestorAdded

    }//GEN-LAST:event_tblPhieuNhapAncestorAdded

    private void tblChonSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChonSanPhamMousePressed
        ThongTinSanPhamForm jdl = new ThongTinSanPhamForm(FormLoading.frm, true);
        jdl.setLocationRelativeTo(pnlChonSP);
        int row = tblChonSanPham.getSelectedRow();
        sanPhamChon = (dtoSanPham) tblChonSanPham.getValueAt(row, 10);
        if (sanPhamChon != null) {

            jdl.sp = sanPhamChon;
            jdl.setVisible(true);
            jdl.chon = 1;//Tạo mới
            fillGioHang(tblGioHang, phieuNhapDangChon.getCtPhieuNhap());
        } else {
            ThongBao.ThongBao("Chưa chọn được sản phẩm! vui lòng chọn lại", "Thông báo");
            jdl.dispose();
        }

    }//GEN-LAST:event_tblChonSanPhamMousePressed

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        int col = tblGioHang.columnAtPoint(evt.getPoint());
        int row = tblGioHang.getSelectedRow();
       
        dtoCTPhieuNhap ct = (dtoCTPhieuNhap) tblGioHang.getValueAt(row, 0);
        if (col == 3) {
            if (phieuNhapDangChon == null) {
                System.out.println("null");
                return;
            }
            if (ct != null) {
                
                if (XoaCTPhieuNhap(ct)) {
                    fillGioHang(tblGioHang, phieuNhapDangChon.getCtPhieuNhap());
                }

            }
        } else if (evt.getClickCount() == 2) {
            ThongTinSanPhamForm jdl = new ThongTinSanPhamForm(FormLoading.frm, true);
            dtoCTPhieuNhap ctPhieuNhap = (dtoCTPhieuNhap) tblGioHang.getValueAt(tblGioHang.getSelectedRow(), 0);
            jdl.sp = ctPhieuNhap.getSp();
            jdl.ctPhieuNhap = ctPhieuNhap;
            jdl.chon = 2;
            jdl.setVisible(true);
            if (jdl.ctPhieuNhap != null) {
                int indexCTPhieuNhap = phieuNhapDangChon.getCtPhieuNhap().indexOf(ctPhieuNhap);
                System.out.println("Index chi tiết phiếu nhập hiện tại: " + indexCTPhieuNhap);
                ctPhieuNhap = jdl.ctPhieuNhap;
                phieuNhapDangChon.getCtPhieuNhap().set(indexCTPhieuNhap, ctPhieuNhap);

                if (UpDatePhieuNhap(phieuNhapDangChon)) {
                    ThongBao.ThongBao("Đã sửa thông tin sản phẩm nhập", "Thông báo");
                    fillGioHang(tblGioHang, phieuNhapDaChon.getCtPhieuNhap());
                }

//            Sau khi đã sửa thông tin phiếu nhập
//            load lại bảng giỏ hàng
            }

        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        fillPhieuNhap(tblPhieuNhap, ListPhieuNhap);
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        int trangThai = 3;
        if (txtTenPhieuNhap.getText().length() < 5) {
            ThongBao.ThongBao("Vui lòng nhập đúng tên phiếu nhập", "Thông báo");
            return;
        }
        if (txtThongTinNCC.getText().trim().isEmpty()) {
            ThongBao.ThongBao("Vui lòng nhập thông tin bên bán!", "Thông báo");
            return;
        }
        String idPhieuNhap = "PN-" + new Date().hashCode();
        String idNCC = "";
        String ghiChuPhieuNhap, tenPhieuNhap, tenNCC;
        ghiChuPhieuNhap = txtThongTinNCC.getText();
        tenPhieuNhap = txtTenPhieuNhap.getText();
        tenNCC = "";

        if (nhaCungCapDangChon != null) {
            idNCC = nhaCungCapDangChon.getIdNCC();
            trangThai = 2;
        }
        System.out.println("Tên nhà cung cấp: " + tenNCC);
        dtoPhieuNhap pn = phieuNhapCtrl.TaoDTOPhieuNhap(ghiChuPhieuNhap, idPhieuNhap, tenPhieuNhap, new Date(), 0, 0, 0, 1, idNCC);
        System.out.println("ghi chu: " + pn.getGhiChuPhieuNhap() + "\n -" + pn.getIdPhieuNhap() + "\n -" + pn.getIdNhaCungCap() + "\n -" + pn.getSoTienTraTruoc() + "\n -" + pn.getTongTienConLai() + "\n -" + pn.getTrangThaiPhieuNhap());
        SetPhieuNhap(ThemPhieuNhap(pn));
        fillGioHang(tblGioHang, phieuNhapDaChon.getCtPhieuNhap());
        TrangThaiGiaoDien(trangThai);
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnTaoPhieuNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuNhapMoiActionPerformed
        if (phieuNhapDangChon != null) {
//            cl.next(pnlChonNhaCungNhapHang);
            int tb = ThongBao.ThongBaoLoai2("Bạn có chắc chắn muốn tạo phiếu nhập mới không?", "Thông báo");
            if (tb == JOptionPane.OK_OPTION) {
                setThongTinNhaCungCap(true);
                phieuNhapDaChon = null;
                phieuNhapDangChon = null;
                clNutbam.show(clNutThaoTac, "card3");
//                cl.show(clNhapHang, "tabTaoMoi");
                TrangThaiGiaoDien(1);
            }

        }
    }//GEN-LAST:event_btnTaoPhieuNhapMoiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jdlChonNhaCungCap jdl = new jdlChonNhaCungCap(FormLoading.frm, true);
        jdl.setVisible(true);
        if (nhaCungCapDangChon != null) {
            String tenNCC = "Tên nhà cung cấp: " + (nhaCungCapDangChon.getTenNCC());
            String dc = "Địa chỉ: " + nhaCungCapDangChon.getDc();
            String sdt = "SDT: " + nhaCungCapDangChon.getSdt();
            String thongTin = tenNCC + "\n" + sdt + "\n" + dc;
            String tenPhieuNhap = "Nhập " + nhaCungCapDangChon.getTenNCC();
            txtTenPhieuNhap.setText(tenPhieuNhap);

            txtThongTinNCC.setText(thongTin);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    public void SetThongTinPhieuNhap(int rowSelect) {
        phieuNhapDangChon = (dtoPhieuNhap) tblPhieuNhap.getValueAt(rowSelect, colPhieuNhapBangPhieuNhap);
        tabPhieuNhap.setSelectedIndex(0);
        txtConLai.setValue(phieuNhapDangChon.getTongTienConLai());
        txtDaThanhToan.setValue(phieuNhapDangChon.getSoTienTraTruoc());
        txtNgayNhap.setDate(phieuNhapDangChon.getNagyTaoPhieuNhap());

        txtTenPhieuNhap.setText(phieuNhapDangChon.getTenPhieuNhap());
        txtThongTinNCC.setText("Tên nhà cung cấp: " + phieuNhapDangChon.getTenNCC());
        clNutbam.show(clNutThaoTac, "card2");
    }

    public double TinhTongTien() {
        List<dtoCTPhieuNhap> list = phieuNhapDangChon.getCtPhieuNhap();
        double tongTien = 0;
        for (dtoCTPhieuNhap ct : list) {
            tongTien += ct.getTongCTPhieuNhap();
        }
        return tongTien;
    }

    public void setThongTinNhaCungCap(boolean flag) {
//        txtTenPhieuNhap.setEnabled(flag);
        txtThongTinNCC.setEnabled(flag);

        txtNgayNhap.setEnabled(flag);

        if (flag) {
//            txtTenPhieuNhap.setText("");
            txtThongTinNCC.setText("");

            txtNgayNhap.setDate(new Date());
            txtDaThanhToan.setValue(0);
            txtConLai.setValue(0);
        }

    }

    public void TrangThaiGiaoDien(int trangThai) {
        switch (trangThai) {
            case 1:
                //Trạng thái ban đầu.
                setThongTinNhaCungCap(true);
                cl.show(clNhapHang, "cl1");
                clNutbam.show(clNutThaoTac, "cl1");
                break;
            case 2:
                // Trạng thái đã có phiếu nhập và có nhà cung cấp
                setThongTinNhaCungCap(false);
                cl.show(clNhapHang, "cl2");
                clNutbam.show(clNutThaoTac, "cl2");

                break;
            case 3:
                // Trạng thái đã có phiếu nhập và không có nhà cung cấp
                nhaCungCapDangChon = null;
                setThongTinNhaCungCap(true);
                cl.show(clNhapHang, "cl2");
                clNutbam.show(clNutThaoTac, "cl2");
                break;
            case 4:
                // Trạng thái đã có phiếu nhập
                break;
//            case 2:
//                // Trạng thái đã có phiếu nhập
//                break;
            default:
            // code block
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapPhieuNhap;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnTaoPhieuNhapMoi;
    public static javax.swing.JComboBox cbbChucNang;
    private javax.swing.JComboBox cbbTrangThaiPhieuNhap;
    public static javax.swing.JPanel clNhapHang;
    private javax.swing.JSplitPane clNhapHangCard2;
    private javax.swing.JPanel clNhaphangCard1;
    private javax.swing.JPanel clNutThaoTac;
    private javax.swing.JPanel clNutThaoTac2;
    private javax.swing.JScrollPane clpBangSP1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblTenBang;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnlChonSP;
    private javax.swing.JPanel pnlThongTinNhaCungCapVaPhieuNhap;
    private javax.swing.JTabbedPane tabPhieuNhap;
    private javax.swing.JTable tblChonSanPham;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JFormattedTextField txtConLai;
    private javax.swing.JFormattedTextField txtDaThanhToan;
    private javax.swing.JTextArea txtLog;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private javax.swing.JTextField txtTenPhieuNhap;
    private javax.swing.JTextArea txtThongTinNCC;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
}
