/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.HoTro;
import BLL.THFormat;
import BLL.phieuNhapCtrl;
import DTO.MyComboBox;
import DTO.donViTinh;
import DTO.dtoCTPhieuNhap;
import DTO.dtoPhieuNhap;
import DTO.dtoSanPham;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author bumte
 */
public class ThongTinSanPhamForm extends javax.swing.JDialog {

    public DTO.dtoSanPham sp = null;
    private dtoPhieuNhap phieuNhap = phieuNhapCtrl.phieuNhapDangChon;
    private static StringBuilder st = new StringBuilder();
    public int chon = 1;
    private double tongTien = 0;
    public dtoCTPhieuNhap ctPhieuNhap = null;

    /**
     * Creates new form ThongTinSanPhamForm
     */
    public ThongTinSanPhamForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTenSP = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtSL = new javax.swing.JSpinner();
        cbbDVT = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JFormattedTextField();
        lblUocLuong2 = new javax.swing.JLabel();
        lblUocLuong1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTenSanPham = new javax.swing.JLabel();
        lblChiTietSP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Tên sản phẩm");

        jScrollPane1.setBorder(null);

        txtTenSP.setEditable(false);
        txtTenSP.setBackground(new java.awt.Color(51, 51, 51));
        txtTenSP.setColumns(20);
        txtTenSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTenSP.setForeground(new java.awt.Color(255, 255, 255));
        txtTenSP.setLineWrap(true);
        txtTenSP.setRows(3);
        txtTenSP.setText("Tên của sản phẩm\n");
        txtTenSP.setWrapStyleWord(true);
        txtTenSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jScrollPane1.setViewportView(txtTenSP);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Số lượng");

        txtSL.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSL.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(1.0d)));
        txtSL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtSLStateChanged(evt);
            }
        });

        cbbDVT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbDVT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbDVT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDVTItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Giá nhập");

        txtGiaNhap.setForeground(new java.awt.Color(0, 0, 102));
        txtGiaNhap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtGiaNhap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGiaNhap.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtGiaNhap.setSelectionEnd(txtGiaNhap.getText().length()-1);
        txtGiaNhap.setValue(0);
        txtGiaNhap.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtGiaNhapCaretUpdate(evt);
            }
        });
        txtGiaNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiaNhapFocusGained(evt);
            }
        });
        txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaNhapActionPerformed(evt);
            }
        });

        lblUocLuong2.setForeground(new java.awt.Color(255, 255, 255));
        lblUocLuong2.setText("jLabel11");

        lblUocLuong1.setForeground(new java.awt.Color(255, 255, 255));
        lblUocLuong1.setText("jLabel11");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tổng tiền");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 102, 51));
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien.setText("120,000,000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("XÁC NHẬN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("HỦY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblUocLuong2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUocLuong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiaNhap)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUocLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUocLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        lblTenSanPham.setText("jLabel2");

        lblChiTietSP.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addComponent(lblChiTietSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChiTietSP, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbDVTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDVTItemStateChanged
//        if (cbbDVT.getItemCount() > 2) {
//            double sl = HoTro.StringToDouble(txtSL.getValue().toString());
//            tinhToanSLTheoTungDonViTinh(sl, cbbDVT);
//
//        }
    }//GEN-LAST:event_cbbDVTItemStateChanged

    private void txtGiaNhapCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtGiaNhapCaretUpdate
        SetTongTien();
    }//GEN-LAST:event_txtGiaNhapCaretUpdate

    private void txtGiaNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaNhapFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaNhapFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ctPhieuNhap = null;

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setThongTinSanPham();
        fillCBBDonViTinh(cbbDVT, sp);

        if (chon == 2) {
            for (int i = 0; i < cbbDVT.getItemCount(); i++) {
                String dvt = cbbDVT.getItemAt(i).toString();
                if (dvt.equals(ctPhieuNhap.getDonViNhap())) {
                    cbbDVT.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaNhapActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        switch (chon) {
            case 1:
                ActionThem();
                break;
            case 2:
                ActionUpDate();
                break;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtSLStateChanged
        SetTongTien();
    }//GEN-LAST:event_txtSLStateChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if (chon == 2) {
            txtSL.setValue(ctPhieuNhap.getSoLuong());
            txtGiaNhap.setValue(ctPhieuNhap.getDonGiaNhap());
            String donViNhap = ctPhieuNhap.getDonViNhap();

            lblTongTien.setText(HoTro.DoubleToString(ctPhieuNhap.getTongCTPhieuNhap()));

        }

        System.out.println("Showed");
    }//GEN-LAST:event_formComponentShown
    public void setThongTinSanPham() {
        String tenSP = "<html>"
                + "<span>"
                + sp.getTenSanPham()
                + "</span>"
                + ""
                + "<html>";

        lblTenSanPham.setText(tenSP);
        String dvtinh = sp.getDonViTinh();
        donViTinh dvt = new donViTinh(dvtinh);
        String quyCach = sp.getTtSanPham().getQuyCach();
        double day = sp.getTtSanPham().getDoDay();
        double dai = sp.getTtSanPham().getDai();
        String ten = sp.getTenSanPham();

        String tenNCC = sp.getTenNhaCungCap();
        String tenSP2 = ten + " " + tenNCC + "\n" + quyCach + "x" + dai + "x" + day;

        txtTenSP.setText(tenSP2);

    }

    public void ActionThem() {
        dtoCTPhieuNhap ctpnMoiTao = TaoCTPhieuNhap();
        boolean themVaoDB = phieuNhapCtrl.ThemChiTietPhieuNhap(ctpnMoiTao);
        if (themVaoDB) {
            this.dispose();
        }
    }

    public dtoCTPhieuNhap TaoCTPhieuNhap() {
        try {
            String idPN = phieuNhap.getIdPhieuNhap();

            double donGiaNhap = HoTro.StringToDouble(txtGiaNhap.getValue().toString());
            double sl = HoTro.StringToDouble(txtSL.getValue().toString());
            SetTongTien();
            String idSP = sp.getIdSanPham();

            String donViNhap = cbbDVT.getSelectedItem().toString();
            dtoCTPhieuNhap ctPhieuNhap = new dtoCTPhieuNhap(donGiaNhap, sl, tongTien, phieuNhap.getIdPhieuNhap(), idSP, txtTenSP.getText(), donViNhap);

            return ctPhieuNhap;
        } catch (Exception e) {
            System.out.println("Lỗi tạo phiếu nhập");
            System.out.println(e.getStackTrace().toString());
            return null;
        }
    }

    public void ActionUpDate() {
        double donGiaNhap = HoTro.StringToDouble(txtGiaNhap.getValue().toString());
//        double tongTien = tongTien;
        double sl = HoTro.StringToDouble(txtSL.getValue().toString());
        String donViNhap = cbbDVT.getSelectedItem().toString();
        SetTongTien();
        ctPhieuNhap.setDonGiaNhap(donGiaNhap);
        ctPhieuNhap.setDonViNhap(donViNhap);
        ctPhieuNhap.setSoLuong(sl);
        ctPhieuNhap.setTongCTPhieuNhap(tongTien);
        this.dispose();

    }

    public void SetTongTien() {
        double donGiaNhap = HoTro.StringToDouble(txtGiaNhap.getValue().toString());
        double sl = HoTro.StringToDouble(txtSL.getValue().toString());
        tongTien = donGiaNhap * sl;
        lblTongTien.setText(HoTro.DoubleToString(tongTien) + "VND");
    }

    public Object[] fillCBBDonViTinh(JComboBox cbb, dtoSanPham sp) {
        donViTinh dv = new donViTinh(sp.getDonViTinh());
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbb.getModel();
        double dai, trongLuong, dvt;
        String Dai, TLuong, Dvt;

        cbbModel.removeAllElements();

        dai = sp.getTtSanPham().getDai();
        trongLuong = sp.getTtSanPham().getTrongLuong();
        dvt = 1;

        Dai = dv.getDai();
        TLuong = dv.getTrongLuong();
        Dvt = dv.getDvtSi();

        MyComboBox mbDai = new MyComboBox(dai, Dai);
        MyComboBox mbTrongLuong = new MyComboBox(trongLuong, TLuong);
        MyComboBox mbDvt = new MyComboBox(dvt, Dvt);

        cbbModel.addElement(mbDvt);
        cbbModel.addElement(mbDai);
        cbbModel.addElement(mbTrongLuong);

        Object[] list = {mbDvt, mbDai, mbTrongLuong};
        list = list;
        return list;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongTinSanPhamForm dialog = new ThongTinSanPhamForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbDVT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChiTietSP;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblUocLuong1;
    private javax.swing.JLabel lblUocLuong2;
    private javax.swing.JFormattedTextField txtGiaNhap;
    private javax.swing.JSpinner txtSL;
    private javax.swing.JTextArea txtTenSP;
    // End of variables declaration//GEN-END:variables
}
